name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Run tests
        run: ctest --test-dir build

      - name: Generate Docs
        run: doxygen doxygen/Doxyfile

      - name: Deploy Docs
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
